import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from datetime import datetime
from typing import Dict, List, Any
from io import BytesIO


class ExcelReportGenerator:
    @staticmethod
    def create_report(statement: Dict[str, Any], transactions: List[Dict[str, Any]]) -> BytesIO:
        """
        Generates an Excel spreadsheet with 3 sheets exactly per the assignment spec:
          Sheet 1 — Account Details
          Sheet 2 — Transaction Ledger with Categorization
          Sheet 3 — Category-Wise Summary & Analytics
        Returns a BytesIO binary stream.
        """
        wb = openpyxl.Workbook()
        wb.remove(wb.active)

        # ------------------------------------------------------------------
        # Shared styles
        # ------------------------------------------------------------------
        HDR_BLUE = "1F497D"
        LIGHT_BLUE = "DCE6F1"
        ZEBRA = "F2F5F8"
        GREEN = "00AA00"
        RED = "CC0000"

        def _fill(hex_color: str) -> PatternFill:
            return PatternFill(start_color=hex_color, end_color=hex_color, fill_type="solid")

        def _font(bold=False, size=11, color="000000", italic=False) -> Font:
            return Font(name="Calibri", size=size, bold=bold, color=color, italic=italic)

        thin = Side(border_style="thin", color="C0C0C0")
        BORDER = Border(left=thin, right=thin, top=thin, bottom=thin)

        C = Alignment(horizontal="center", vertical="center")
        L = Alignment(horizontal="left",   vertical="center")
        R = Alignment(horizontal="right",  vertical="center")
        WRAP = Alignment(horizontal="left", vertical="center", wrap_text=True)

        CURR = "#,##0.00"
        INT  = "#,##0"

        def _header_row(ws, row: int, values: list):
            for col, val in enumerate(values, 1):
                c = ws.cell(row=row, column=col, value=val)
                c.font      = _font(bold=True, color="FFFFFF")
                c.fill      = _fill(HDR_BLUE)
                c.alignment = C
                c.border    = BORDER

        def _auto_width(ws):
            for col in ws.columns:
                max_len = 0
                col_letter = get_column_letter(col[0].column)
                for cell in col:
                    if type(cell).__name__ == "MergedCell":
                        continue
                    if cell.value:
                        for line in str(cell.value).split("\n"):
                            max_len = max(max_len, len(line))
                ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

        acc = statement.get("accountDetails", {})
        analytics = statement.get("analytics", {})

        # ------------------------------------------------------------------ #
        #  SHEET 1 — Account Details                                          #
        # ------------------------------------------------------------------ #
        ws1 = wb.create_sheet(title="Account Details")
        ws1.column_dimensions["A"].width = 32
        ws1.column_dimensions["B"].width = 38

        # Title banner
        ws1.merge_cells("A1:B1")
        t = ws1["A1"]
        t.value     = "HDFC BANK STATEMENT — ACCOUNT DETAILS"
        t.font      = _font(bold=True, size=14, color=HDR_BLUE)
        t.alignment = C
        t.fill      = _fill(LIGHT_BLUE)
        ws1.row_dimensions[1].height = 30

        ws1.merge_cells("A2:B2")
        sub = ws1["A2"]
        sub.value     = f"Generated by Correm Bank Statement Analyzer • {datetime.now().strftime('%d %b %Y, %H:%M')}"
        sub.font      = _font(italic=True, size=9, color="888888")
        sub.alignment = C
        ws1.row_dimensions[2].height = 16

        def _kv(ws, row, key, value, value_font=None, value_fmt=None):
            kc = ws.cell(row=row, column=1, value=key)
            kc.font      = _font(bold=True)
            kc.fill      = _fill(ZEBRA)
            kc.border    = BORDER
            kc.alignment = L

            vc = ws.cell(row=row, column=2, value=value)
            vc.font      = value_font or _font()
            vc.border    = BORDER
            vc.alignment = L
            if value_fmt:
                vc.number_format = value_fmt
            return vc

        # Section: Account Metadata
        r = 4
        ws1.merge_cells(f"A{r}:B{r}")
        ws1.cell(r, 1, "ACCOUNT METADATA").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1

        _kv(ws1, r, "Account Holder Name",   acc.get("accountHolderName", "N/A"))
        r += 1
        _kv(ws1, r, "Account Number",         acc.get("accountNumber", "N/A"))
        r += 1
        _kv(ws1, r, "Bank Name & Branch",
            f"{acc.get('bankName', 'HDFC Bank')} — {acc.get('branchName', 'N/A')}")
        r += 1
        _kv(ws1, r, "IFSC Code",              acc.get("ifsc", "N/A"))
        r += 1

        period = f"{acc.get('startDate', 'N/A')} to {acc.get('endDate', 'N/A')}"
        _kv(ws1, r, "Statement Period (From — To)", period)
        r += 1

        recon_val = acc.get("reconciliationStatus", "PENDING")
        recon_color = GREEN if recon_val == "SUCCESS" else RED
        _kv(ws1, r, "Reconciliation Status", recon_val,
            value_font=_font(bold=True, color=recon_color))
        r += 2

        # Section: Financial Summary
        ws1.merge_cells(f"A{r}:B{r}")
        ws1.cell(r, 1, "FINANCIAL SUMMARY").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1

        ob_cell = _kv(ws1, r, "Opening Balance",
                      acc.get("openingBalance", 0.0),
                      value_font=_font(bold=True), value_fmt=CURR)
        ob_cell.fill = _fill(LIGHT_BLUE)
        r += 1

        total_cr   = analytics.get("totalCredits", 0.0)
        credit_cnt = analytics.get("creditCount", 0)
        cr_cell = _kv(ws1, r, f"Total Credits (+)  [{credit_cnt} transactions]",
                      total_cr, value_font=_font(bold=True, color=GREEN), value_fmt=CURR)
        r += 1

        total_dr   = analytics.get("totalDebits", 0.0)
        debit_cnt  = analytics.get("debitCount", 0)
        dr_cell = _kv(ws1, r, f"Total Debits (-)  [{debit_cnt} transactions]",
                      total_dr, value_font=_font(bold=True, color=RED), value_fmt=CURR)
        r += 1

        _kv(ws1, r, "Net Cash Flow",
            analytics.get("netFlow", 0.0),
            value_font=_font(bold=True), value_fmt=CURR)
        r += 1

        _kv(ws1, r, "Transaction Count", analytics.get("transactionCount", 0),
            value_fmt=INT)
        r += 1

        cb_cell = _kv(ws1, r, "Closing Balance",
                      acc.get("closingBalance", 0.0),
                      value_font=_font(bold=True), value_fmt=CURR)
        cb_cell.fill = _fill(LIGHT_BLUE)

        # ------------------------------------------------------------------ #
        #  SHEET 2 — Transaction Ledger                                       #
        # ------------------------------------------------------------------ #
        ws2 = wb.create_sheet(title="Transaction Ledger")
        ws2.freeze_panes = "A2"
        ws2.row_dimensions[1].height = 25

        headers2 = [
            "Date", "Value Date", "Description",
            "Cheque / Ref No.", "Deposits (CR)", "Withdrawals (DR)",
            "Running Balance", "Category"
        ]
        _header_row(ws2, 1, headers2)

        # Column widths
        for col, w in zip("ABCDEFGH", [14, 14, 50, 20, 18, 18, 18, 22]):
            ws2.column_dimensions[get_column_letter(col.encode()[0] - 64)].width = w

        for r_idx, tx in enumerate(transactions, 2):
            ws2.row_dimensions[r_idx].height = 18
            fill = _fill(ZEBRA) if r_idx % 2 == 1 else None

            def _cell(col, val, align=C, fmt=None, fnt=None):
                c = ws2.cell(row=r_idx, column=col, value=val)
                c.alignment = align
                c.border    = BORDER
                c.font      = fnt or _font()
                if fill:
                    c.fill = fill
                if fmt:
                    c.number_format = fmt
                return c

            _cell(1, tx.get("date"))
            _cell(2, tx.get("valueDate"))
            _cell(3, tx.get("description"), align=WRAP)
            _cell(4, tx.get("reference") or "")

            dr_val = tx.get("debit", 0.0) or 0.0
            cr_val = tx.get("credit", 0.0) or 0.0

            cr_c = _cell(5, cr_val if cr_val else None, align=R, fmt=CURR,
                         fnt=_font(color=GREEN) if cr_val else _font(color="AAAAAA"))
            dr_c = _cell(6, dr_val if dr_val else None, align=R, fmt=CURR,
                         fnt=_font(color=RED) if dr_val else _font(color="AAAAAA"))
            _cell(7, tx.get("balance"), align=R, fmt=CURR, fnt=_font(bold=True))

            cat = tx.get("category", "Other")
            _cell(8, cat, fnt=_font(
                bold=True,
                color="008800" if cat == "Salary" else ("CC0000" if cat in ("EMI / Loan", "Cash Withdrawal") else "1F497D")
            ))

        # ------------------------------------------------------------------ #
        #  SHEET 3 — Category-Wise Summary & Analytics                        #
        # ------------------------------------------------------------------ #
        ws3 = wb.create_sheet(title="Analytics Summary")
        ws3.column_dimensions["A"].width = 28
        ws3.column_dimensions["B"].width = 22
        ws3.column_dimensions["C"].width = 22
        ws3.column_dimensions["D"].width = 18
        ws3.column_dimensions["E"].width = 18

        r = 1
        ws3.merge_cells(f"A{r}:E{r}")
        h = ws3[f"A{r}"]
        h.value     = "CATEGORY-WISE SUMMARY & ANALYTICS REPORT"
        h.font      = _font(bold=True, size=14, color=HDR_BLUE)
        h.alignment = C
        h.fill      = _fill(LIGHT_BLUE)
        ws3.row_dimensions[r].height = 28
        r += 2

        # --- 3.1 Category Breakdown ---
        ws3.cell(r, 1, "CATEGORY BREAKDOWN").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1
        _header_row(ws3, r, ["Category", "Total Debits (DR)", "Total Credits (CR)", "Transaction Count"])
        r += 1
        for cat in analytics.get("categorySummary", []):
            ws3.cell(r, 1, cat.get("category")).border  = BORDER
            ws3.cell(r, 1).font      = _font()
            ws3.cell(r, 1).alignment = L

            dc = ws3.cell(r, 2, cat.get("debit", 0.0))
            dc.number_format = CURR; dc.alignment = R; dc.border = BORDER; dc.font = _font(color=RED if cat.get("debit", 0) > 0 else "000000")

            cc = ws3.cell(r, 3, cat.get("credit", 0.0))
            cc.number_format = CURR; cc.alignment = R; cc.border = BORDER; cc.font = _font(color=GREEN if cat.get("credit", 0) > 0 else "000000")

            tc = ws3.cell(r, 4, cat.get("count", 0))
            tc.alignment = C; tc.border = BORDER; tc.font = _font()

            if r % 2 == 0:
                for col in range(1, 5):
                    ws3.cell(r, col).fill = _fill(ZEBRA)
            r += 1

        r += 1

        # --- 3.2 Month-wise Breakdown ---
        ws3.cell(r, 1, "MONTH-WISE CASH FLOW").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1
        _header_row(ws3, r, ["Month", "Total Inflow (CR)", "Total Outflow (DR)", "Net Cash Flow", "Tx Count"])
        r += 1
        for m in analytics.get("monthlySummary", []):
            ws3.cell(r, 1, m.get("month")).border = BORDER; ws3.cell(r, 1).alignment = C; ws3.cell(r, 1).font = _font()

            for col_i, key, fmt, clr in [
                (2, "credit", CURR, GREEN), (3, "debit", CURR, RED),
                (4, "net", CURR, "1F497D"), (5, "count", INT, "000000")
            ]:
                c = ws3.cell(r, col_i, m.get(key, 0))
                c.number_format = fmt; c.alignment = R; c.border = BORDER
                c.font = _font(color=clr)
            if r % 2 == 0:
                for col in range(1, 6):
                    ws3.cell(r, col).fill = _fill(ZEBRA)
            r += 1
        r += 1

        # --- 3.3 Top 5 Largest Transactions ---
        ws3.cell(r, 1, "TOP 5 LARGEST TRANSACTIONS").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1
        _header_row(ws3, r, ["Date", "Description", "Deposits (CR)", "Withdrawals (DR)", "Category"])
        r += 1
        top5 = analytics.get("top5Transactions", [])
        if not top5:
            ws3.merge_cells(f"A{r}:E{r}")
            ws3.cell(r, 1, "No transactions available").alignment = C
            ws3.cell(r, 1).font = _font(italic=True, color="888888")
            r += 1
        else:
            for tx in top5:
                for col_i, val, align in [
                    (1, tx.get("date", ""), C),
                    (2, tx.get("description", ""), L),
                    (3, tx.get("credit") or None, R),
                    (4, tx.get("debit") or None, R),
                    (5, tx.get("category", "Other"), C),
                ]:
                    c = ws3.cell(r, col_i, val)
                    c.alignment = align; c.border = BORDER; c.font = _font()
                    if col_i in (3, 4) and val:
                        c.number_format = CURR
                        c.font = _font(bold=True, color=GREEN if col_i == 3 else RED)
                r += 1
        r += 1

        # --- 3.4 Salary Detection ---
        ws3.cell(r, 1, "SALARY DETECTION REPORT").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1
        _header_row(ws3, r, ["Source / Employer", "Estimated Amount", "Frequency", "Confidence Score"])
        r += 1
        salaries = analytics.get("salaryDetection", [])
        if not salaries:
            ws3.merge_cells(f"A{r}:D{r}")
            ws3.cell(r, 1, "No salary transactions auto-detected").alignment = C
            ws3.cell(r, 1).font = _font(italic=True, color="888888")
            r += 1
        else:
            for sal in salaries:
                ws3.cell(r, 1, sal.get("source", "")).border = BORDER; ws3.cell(r, 1).alignment = L
                a = ws3.cell(r, 2, sal.get("amount", 0.0))
                a.number_format = CURR; a.alignment = R; a.border = BORDER; a.font = _font(bold=True, color=GREEN)
                ws3.cell(r, 3, sal.get("frequency", "")).alignment = C; ws3.cell(r, 3).border = BORDER
                c_sc = ws3.cell(r, 4, f"{int(sal.get('confidence', 0) * 100)}%")
                c_sc.alignment = C; c_sc.border = BORDER
                r += 1
        r += 1

        # --- 3.5 EMI / Recurring Debit Detection ---
        ws3.cell(r, 1, "EMI / RECURRING DEBIT DETECTION").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1
        _header_row(ws3, r, ["Source / Lender", "EMI Amount", "Frequency", "Confidence Score"])
        r += 1
        emis = analytics.get("emiDetection", [])
        if not emis:
            ws3.merge_cells(f"A{r}:D{r}")
            ws3.cell(r, 1, "No recurring EMI/loan transactions auto-detected").alignment = C
            ws3.cell(r, 1).font = _font(italic=True, color="888888")
            r += 1
        else:
            for emi in emis:
                ws3.cell(r, 1, emi.get("source", "")).border = BORDER; ws3.cell(r, 1).alignment = L
                a = ws3.cell(r, 2, emi.get("amount", 0.0))
                a.number_format = CURR; a.alignment = R; a.border = BORDER; a.font = _font(bold=True, color=RED)
                ws3.cell(r, 3, emi.get("frequency", "")).alignment = C; ws3.cell(r, 3).border = BORDER
                c_sc = ws3.cell(r, 4, f"{int(emi.get('confidence', 0) * 100)}%")
                c_sc.alignment = C; c_sc.border = BORDER
                r += 1
        r += 1

        # --- 3.6 Categorization Statistics ---
        ws3.cell(r, 1, "CATEGORIZATION STATISTICS").font = _font(bold=True, size=12, color=HDR_BLUE)
        r += 1
        pct = analytics.get("categorizationPercentage", 0.0)
        ws3.cell(r, 1, "System Categorization Coverage:").font = _font(bold=True)
        ws3.cell(r, 1).border = BORDER; ws3.cell(r, 1).fill = _fill(ZEBRA)
        pct_c = ws3.cell(r, 2, f"{pct}%")
        pct_c.font = _font(bold=True, color=GREEN if pct >= 70 else RED)
        pct_c.border = BORDER
        r += 1
        ws3.cell(r, 1, "Total Transactions:").font = _font(); ws3.cell(r, 1).border = BORDER; ws3.cell(r, 1).fill = _fill(ZEBRA)
        ws3.cell(r, 2, analytics.get("transactionCount", 0)).border = BORDER
        r += 1
        ws3.cell(r, 1, "Credit Transactions:").font = _font(); ws3.cell(r, 1).border = BORDER; ws3.cell(r, 1).fill = _fill(ZEBRA)
        ws3.cell(r, 2, analytics.get("creditCount", 0)).border = BORDER
        r += 1
        ws3.cell(r, 1, "Debit Transactions:").font = _font(); ws3.cell(r, 1).border = BORDER; ws3.cell(r, 1).fill = _fill(ZEBRA)
        ws3.cell(r, 2, analytics.get("debitCount", 0)).border = BORDER

        # Auto-adjust widths
        for ws in wb.worksheets:
            _auto_width(ws)

        output = BytesIO()
        wb.save(output)
        output.seek(0)
        return output
